services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pji
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
